[package]
name = "gba_multiboot_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba = "0.5.3"
voladdress = "1.0.2"
